---
# https://docs.ansible.com/ansible-lint/rules/default_rules.html
skip_list:
  # Lines should be no longer than 160 chars
  - "204"
  # Commands should not change things if nothing needs doing
  - "301"
  # apt-get used in place of apt-get module
  - "303"
  # Shells that use pipes should set the pipefail option
  - "306"
  # Tasks that run when changed should likely be handlers
  - "503"
  # Don't compare to literal True/False
  - "601"
  # Don't compare to empty string
  - "602"
# vim: syntax=yaml
...
