# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  APT_ANSIBLE: "8.1.0"
  APT_JC: "1.23.3"
  APT_JMESPATH: "1.0.1"
  APT_MOLECULE: "5.1.0"
  GIT_STRATEGY: none
  MOLECULE_VERBOSITY: "2"
  PIPX_BIN_DIR: "/usr/local/bin"
  PIPX_HOME: "/opt/pipx"
  PY_COLORS: "1"
before_script:
  - apt-get update -qq
  - apt-get dist-upgrade -qqy
  - apt-get install -qqy ansible git pipx python3-apt python3-pip python3-venv sudo
  - echo 'export PIPX_BIN_DIR="${PIPX_BIN_DIR}"' >> ~/.bashrc
  - echo 'export PIPX_HOME="${PIPX_HOME}"' >> ~/.bashrc
  - source ~/.profile
  - whoami
  - pwd
  - python3 --version
  - pipx --version
  - pipx install --include-deps molecule==${APT_MOLECULE}
  - pipx inject --include-deps --include-apps molecule ansible==${APT_ANSIBLE} jc==${APT_JC} jmespath==${APT_JMESPATH}
  - ls -lah /home/ansible/.local/bin
  - which ansible-galaxy
  - ansible-galaxy --version
  - mkdir -p builds/${CI_PROJECT_ROOT_NAMESPACE}
  - cd builds/${CI_PROJECT_ROOT_NAMESPACE}
  - git clone ${CI_PROJECT_URL}.git
  - cd ${CI_PROJECT_NAME}
stages:
  - bullseye
  - bookworm
  - trixie
  - jammy
trixie:
  image: debian:trixie
  stage: trixie
  script:
    - molecule test
bookworm:
  image: debian:bookworm
  stage: bookworm
  script:
    - molecule test
bullseye:
  image: debian:bullseye-backports
  stage: bullseye
  script:
    - molecule test
jammy:
  image: ubuntu:jammy
  stage: jammy
  script:
    - molecule test
...
