# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Apticron tasks
  block:

    - name: Apticron present for servers with outgoing mail servers
      block:

        - name: Apt apticron preferences absent
          ansible.builtin.file:
            path: /etc/apt/preferences.d/apticron.pref
            state: absent

        - name: Apticron present
          ansible.builtin.apt:
            pkg: "{{ apt_apticron_pkgs }}"
            state: present
            install_recommends: false
            update_cache: true
          when: >-
            ( ( ansible_local.dpkg.sel is not defined ) or
            ( apt_apticron_pkgs | ansible.builtin.difference(ansible_local.dpkg.sel) != [] ) )

      when:
        - inventory_hostname != "localhost"
        - ansible_connection != "chroot"
        - apt_apticron is defined
        - apt_apticron | bool
        - apt_apticron_pkgs is defined
        - apt_apticron_pkgs != []

    - name: Apticron absent for servers without outgoing mail servers
      block:

        - name: Apt apticron preferences present
          ansible.builtin.copy:
            src: apticron.pref
            dest: /etc/apt/preferences.d/apticron.pref
            mode: 0644
            owner: root
            group: root

        - name: Apticron absent
          ansible.builtin.apt:
            pkg: "{{ apt_apticron_pkgs }}"
            state: absent
            purge: true
            autoremove: true
            autoclean: true
            update_cache: true
          register: apt_apticron_absent
          when: >-
            ( ( ansible_local.dpkg.sel is not defined ) or
            ( apt_apticron_pkgs | ansible.builtin.intersect(ansible_local.dpkg.sel) != [] ) )

        - name: Apt clean
          ansible.builtin.include_tasks: apt_clean.yml
          when:
            - ansible_version.full is version('2.13', '>=')
            - apt_apticron_absent.changed is defined
            - apt_apticron_absent.changed | bool

      when: >-
        ( inventory_hostname == "localhost" ) or
        ( ansible_connection == "chroot" ) or
        ( ( apt_apticron is defined ) and
        ( not apt_apticron | bool ) )

  tags:
    - apt
...
