# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Slurp and print file
  block:

    - name: "Slurp {{ apt_file }}"
      ansible.builtin.slurp:
        src: "{{ apt_file }}"
      register: apt_file_contents_b64encoded

    - name: Set fact for .list file contents
      block:

        - name: "Decode the base64 encoded version of {{ apt_file }}"
          ansible.builtin.set_fact:
            apt_file_content_lines: "{{ apt_file_contents_b64encoded['content'] | ansible.builtin.b64decode | trim | ansible.builtin.split('\n') | map('regex_replace', '^#') | map('regex_replace', '^$') }}"

        - name: "Print the contents of {{ apt_file }}"
          ansible.builtin.debug:
            var: apt_file_content_lines

      when: apt_file is regex('[.]list$')

    - name: Set fact for .sources file content
      block:

        - name: "Decode the base64 encoded version of {{ apt_file }}"
          ansible.builtin.set_fact:
            apt_file_content: "{{ apt_file_contents_b64encoded['content'] | ansible.builtin.b64decode | trim | community.general.jc('ini') }}"

        - name: "Print the contents of {{ apt_file }}"
          ansible.builtin.debug:
            var: apt_file_content

      when: apt_file is regex('[.]sources$')

  tags:
    - apt
...
