# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Apt repo list and sources tasks
  block:

    - name: "Directory /etc/apt/sources.list.d present for {{ apt_distro }}"
      ansible.builtin.file:
        path: /etc/apt/sources.list.d
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: "Sources file in place for {{ ansible_distribution }}"
      ansible.builtin.deb822_repository:
        name: "{{ apt_source.name }}"
        types: "{{ apt_source.types }}"
        uris: "{{ apt_source.uris }}"
        suites: "{{ apt_source.suites }}"
        components: "{{ apt_source.components }}"
        signed_by: "{{ apt_source.signed_by }}"
      loop: "{{ apt_sources }}"
      loop_control:
        loop_var: apt_source
        label: "{{ apt_source.name }}"
      when:
        - apt_sources is defined
        - apt_sources != []
        - apt_source.state is defined
        - apt_source.state == "present"

    - name: "List files in place for {{ ansible_distribution }}"
      ansible.builtin.template:
        src: sources.list.j2
        dest: "{{ apt_list.path }}"
        mode: "0644"
        owner: root
        group: root
        backup: true
      vars:
        apt_file_dest: "/etc/apt/sources.list.d/{{ ansible_distribution | lower }}.sources"
      loop: "{{ apt_lists }}"
      loop_control:
        loop_var: apt_list
        label: "{{ apt_list.path | ansible.builtin.basename | ansible.builtin.regex_replace('[.]lists$') }}"
      when:
        - apt_lists is defined
        - apt_lists != []
        - apt_list.state is defined
        - apt_list.state == "present"

    - name: Include apt list files absent tasks
      ansible.builtin.include_tasks: file_absent.yml
      vars:
        apt_file_absent: "{{ apt_lists_file_absent.path }}"
      loop: "{{ apt_lists }}"
      loop_control:
        loop_var: apt_lists_file_absent
        label: "{{ apt_lists_file_absent.path | ansible.builtin.basename | ansible.builtin.regex_replace('[.]lists$') }}"
      when:
        - apt_lists is defined
        - apt_lists != []
        - apt_lists_file_absent.path is defined
        - apt_lists_file_absent.state is defined
        - apt_lists_file_absent.state == "absent"

    - name: Include apt source files absent tasks
      ansible.builtin.include_tasks: file_absent.yml
      vars:
        apt_file_absent: "/etc/apt/sources.list.d/{{ apt_sources_file_absent.name }}.sources"
      loop: "{{ apt_sources }}"
      loop_control:
        loop_var: apt_sources_file_absent
        label: "{{ apt_sources_file_absent.name }}"
      when:
        - apt_sources is defined
        - apt_sources != []
        - apt_sources_file_absent.name is defined
        - apt_sources_file_absent.state is defined
        - apt_sources_file_absent.state == "absent"

    - name: "Set facts for {{ apt_distro }}"
      ansible.builtin.set_fact:
        apt_backports: "{{ apt_sources | community.general.json_query(apt_backports_jmespath_query) }}"
        apt_components: "{{ apt_sources | community.general.json_query(apt_components_jmespath_query) }}"
        apt_domain: "{{ apt_sources | community.general.json_query(apt_domain_jmespath_query) }}"
        apt_file: "{{ apt_sources | community.general.json_query(apt_file_jmespath_query) }}"
        apt_files_absent: "{{ apt_sources | community.general.json_query(apt_files_absent_jmespath_query) }}"
        apt_https: "{{ apt_sources | community.general.json_query(apt_https_jmespath_query) }}"
        apt_signed_by: "{{ apt_sources | community.general.json_query(apt_signed_by_jmespath_query) }}"
        apt_src: "{{ apt_sources | community.general.json_query(apt_src_jmespath_query) }}"
      vars:
        apt_backports_jmespath_query: "[?name=='{{ apt_distro }}'].backports|[0]"
        apt_components_jmespath_query: "[?name=='{{ apt_distro }}'].components|[]"
        apt_domain_jmespath_query: "[?name=='{{ apt_distro }}'].domain|[0]"
        apt_file_jmespath_query: "[?name=='{{ apt_distro }}'].file|[0]"
        apt_files_absent_jmespath_query: "[?name=='{{ apt_distro }}'].files_absent|[]"
        apt_https_jmespath_query: "[?name=='{{ apt_distro }}'].https|[0]"
        apt_signed_by_jmespath_query: "[?name=='{{ apt_distro }}'].signed_by|[0]"
        apt_src_jmespath_query: "[?name=='{{ apt_distro }}'].src|[0]"

    - name: "Debug apt_backports for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_backports
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_components for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_components
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_domain for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_domain
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_file for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_file
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_files_absent for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_files_absent
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_https for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_https
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_signed_by for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_signed_by
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: "Debug apt_src for {{ apt_distro }}"
      ansible.builtin.debug:
        var: apt_src
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: Only .list and .sources files are supported
      ansible.builtin.assert:
        that: >-
          ( apt_file == "/etc/apt/sources.list.d/debian.sources" ) or
          ( apt_file == "/etc/apt/sources.list.d/ubuntu.sources" ) or
          ( apt_file == "/etc/apt/sources.list" )
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Check that the signed-by file exists
      ansible.builtin.stat:
        path: "{{ apt_signed_by }}"
      register: apt_signed_by_path

    - name: The Signed-By GPG public keys ring needs to exist
      ansible.builtin.assert:
        that:
          - apt_signed_by_path.stat.exists | bool
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Stat /etc/apt/sources.list
      ansible.builtin.stat:
        path: /etc/apt/sources.list
      register: apt_distro_sources_list

    - name: Include slurp and print file tasks
      ansible.builtin.include_tasks: check_file.yml
      vars:
        apt_file: /etc/apt/sources.list
      when: apt_distro_sources_list.stat.exists | bool

    - name: "Stat {{ apt_file }}"
      ansible.builtin.stat:
        path: "{{ apt_file }}"
      vars:
        apt_file: "/etc/apt/sources.list.d/{{ ansible_distribution | lower }}.sources"
      register: apt_distro_sources

    - name: Include slurp and print file tasks
      ansible.builtin.include_tasks: check_file.yml
      vars:
        apt_file: "/etc/apt/sources.list.d/{{ ansible_distribution | lower }}.sources"
      when: apt_distro_sources.stat.exists | bool

    - name: "File /etc/apt.conf in place for {{ apt_distro }}"
      ansible.builtin.template:
        src: templates/apt.conf.j2
        dest: /etc/apt.conf
        mode: "0644"
        owner: root
        group: root
        backup: true

  tags:
    - apt
...
