---
- name: Load package information as facts
  package_facts:
    manager: apt
  tags:
    - apt

- name: Fail if ansible_facts.packages is not defined or empty
  fail:
    msg: The package_facts array is empty, this could be a result of the Ansible 2.8.x bug https://github.com/ansible/ansible/issues/56921
  when: ( ansible_facts.packages is not defined ) or ( ansible_facts.packages == [] )
  tags:
    - apt

- name: apt-transport-https present
  apt:
    pkg:
      - apt-transport-https
    state: present
    update_cache: false
  when: ( "apt-transport-https" not in ansible_facts.packages ) and ( apt_distro != "jessie" )
  tags:
    - apt

- name: Various /etc/apt/sources.list.d/ files absent
  file:
    path: "/etc/apt/sources.list.d/{{ file }}"
    state: absent
  loop: "{{ apt_debian_sources_absent }}"
  loop_control:
    loop_var: file
  when: ( apt_debian_sources_absent is defined ) and ( apt_debian_sources_absent != [] )
  tags:
    - apt

# Gandi servers don't have /etc/apt/sources.list and have HTTPS enabled already
- name: Stat /etc/apt/sources.list
  stat:
    path: "/etc/apt/sources.list"
  register: sources_list
  tags:
    - apt

- name: /etc/apt/sources.list in place
  template:
    src: templates/debian_sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    backup: true
  when: sources_list.stat.exists == True
  tags:
    - apt

- name: /etc/apt.conf in place
  template:
    src: templates/apt.conf.j2
    dest: /etc/apt.conf
    mode: 0644
    backup: true
  tags:
    - apt

- name: Update the cache when switching distros
  apt:
    update_cache: true
  when: ( apt_distro_switch is defined ) and ( apt_distro_switch == True )
  tags:
    - apt

- name: When switching distros updates should not be done via Ansible
  block:

    - name: Packages upgraded
      apt:
        autoclean: true
        autoremove: true
        upgrade: dist
        update_cache: true
      tags:
        - apt

    - name: Packages present
      apt:
        pkg:
          - apticron
          - aptitude
          - apt-listchanges
          - apt-show-versions
          - python-apt
        state: present
        update_cache: false
      tags:
        - apt

  when: ( apt_distro_switch is not defined ) or ( apt_distro_switch == False )
...
