---
- name: Load package information as facts
  package_facts:
    manager: apt

- name: apt-transport-https present
  apt:
    pkg:
      - apt-transport-https
    state: present
    update_cache: no 
  when: "apt-transport-https" not in ansible_facts.packages

# Gandi servers don't have /etc/apt/sources.list and have HTTPS enabled already
- name: Stat /etc/apt/sources.list
  stat:
    path: "/etc/apt/sources.list"
  register: sources_list

- name: /etc/apt/sources.list in place
  template:
    src: templates/debian_sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    backup: yes
  when: sources_list.stat.exists == True

- name: Packages present
  apt:
    pkg:
      - apt-transport-https
      - apticron
      - aptitude
      - apt-listchanges
      - apt-show-versions
    state: present
    update_cache: yes
