---
- name: Debian tasks
  block:

    - name: apt-transport-https present
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
        state: present
        update_cache: false
      when: apt_distro is not regex(^jessie|stretch$')

    - name: Various /etc/apt/sources.list.d/ files absent
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/{{ file }}"
        state: absent
      loop: "{{ apt_debian_sources_absent }}"
      loop_control:
        loop_var: file
      when: ( apt_debian_sources_absent is defined ) and ( apt_debian_sources_absent != [] )

    # Debian servers from Gandi don't have /etc/apt/sources.list and have HTTPS enabled already
    - name: Stat /etc/apt/sources.list
      ansible.builtin.stat:
        path: "/etc/apt/sources.list"
      register: sources_list

    - name: /etc/apt/sources.list in place
      ansible.builtin.template:
        src: "debian_{{ apt_distro }}.list.j2"
        dest: /etc/apt/sources.list
        mode: 0644
        owner: root
        group: root
        backup: false
      when: sources_list.stat.exists

    - name: /etc/apt.conf in place
      ansible.builtin.template:
        src: templates/apt.conf.j2
        dest: /etc/apt.conf
        mode: 0644
        owner: root
        group: root
        backup: false

  tags:
    - apt
...
