# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Debian tasks
  block:

    - name: Various /etc/apt/sources.list.d/ files absent
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/{{ apt_sources_file }}"
        state: absent
      loop: "{{ apt_debian_sources_absent }}"
      loop_control:
        loop_var: apt_sources_file
      when:
        - apt_debian_sources_absent is defined
        - apt_debian_sources_absent != []

    - name: Set facts for the Debian version
      ansible.builtin.set_fact:
        apt_debian_backports: "{{ apt_debian | community.general.json_query(apt_debian_backports_jmespath_query) }}"
        apt_debian_components: "{{ apt_debian | community.general.json_query(apt_debian_components_jmespath_query) }}"
        apt_debian_domain: "{{ apt_debian | community.general.json_query(apt_debian_domain_jmespath_query) }}"
        apt_debian_format: "{{ apt_debian | community.general.json_query(apt_debian_format_jmespath_query) }}"
        apt_debian_src: "{{ apt_debian | community.general.json_query(apt_debian_src_jmespath_query) }}"
      vars:
        apt_debian_backports_jmespath_query: "[?name=='{{ apt_distro }}'].backports|[0]"
        apt_debian_components_jmespath_query: "[?name=='{{ apt_distro }}'].components|[]"
        apt_debian_domain_jmespath_query: "[?name=='{{ apt_distro }}'].domain|[0]"
        apt_debian_format_jmespath_query: "[?name=='{{ apt_distro }}'].format|[0]"
        apt_debian_src_jmespath_query: "[?name=='{{ apt_distro }}'].src|[0]"

    - name: Print the components to be enabled
      ansible.builtin.debug:
        var: apt_debian_components
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: Use /etc/apt/sources.list
      block:

        - name: File /etc/apt/sources.list in place
          ansible.builtin.template:
            src: "debian.list.j2"
            dest: /etc/apt/sources.list
            mode: "0644"
            owner: root
            group: root
            backup: true

        - name: File /etc/apt/sources.list.d/debian.sources absent
          ansible.builtin.command: >-
            mv
            /etc/apt/sources.list.d/debian.sources
            /etc/apt/sources.list.d/.debian.sources.{{ ansible_date_time.iso8601_basic_short }}.ansible.save"
          changed_when: true
          when:
            - apt_sources_list is defined
            - apt_sources_list.stat.exists | bool

      when: apt_debian_format == "list"

    - name: Use /etc/apt/sources.list.d/debian.sources
      block:

        - name: File /etc/apt/sources.list.d/debian.sources in place
          ansible.builtin.template:
            src: "debian.sources.j2"
            dest: /etc/apt/sources.list.d/debian.sources.j2
            mode: "0644"
            owner: root
            group: root
            backup: true

        - name: File /etc/apt/sources.list absent
          ansible.builtin.command: >-
            mv
            /etc/apt/sources.list
            /etc/apt/.sources.list.{{ ansible_date_time.iso8601_basic_short }}.ansible.save
          changed_when: true
          when:
            - apt_sources_list_d_paths is defined
            - ( "debian.sources" in apt_sources_list_d_paths )

      when: apt_debian_format == "sources"

    - name: File /etc/apt/sources.list in place
      ansible.builtin.template:
        src: "debian_{{ apt_distro }}.list.j2"
        dest: /etc/apt/sources.list
        mode: "0644"
        owner: root
        group: root
        backup: true
      # Debian servers from Gandi don't have /etc/apt/sources.list and have HTTPS enabled already
      when: apt_sources_list.stat.exists | bool

    - name: File /etc/apt.conf in place
      ansible.builtin.template:
        src: templates/apt.conf.j2
        dest: /etc/apt.conf
        mode: "0644"
        owner: root
        group: root
        backup: true

  tags:
    - apt
...
