# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Sources list file tasks
  block:

    - name: "List files in place for {{ ansible_facts.distribution }}"
      ansible.builtin.template:
        src: sources.list.j2
        dest: "{{ apt_list.path }}"
        mode: "0644"
        owner: root
        group: root
        backup: true
      vars:
        apt_file_dest: "/etc/apt/sources.list.d/{{ ansible_facts.distribution | lower }}.sources"
      when:
        - apt_list.state is defined
        - apt_list.state == "present"
      loop: "{{ apt_lists }}"
      loop_control:
        loop_var: apt_list
        label: "{{ apt_list.path | ansible.builtin.basename | ansible.builtin.regex_replace('[.]lists$') }}"

    - name: "Include apt list files absent tasks for {{ ansible_facts.distribution }}"
      ansible.builtin.include_tasks: file_absent.yml
      vars:
        apt_file_absent: "{{ apt_lists_file_absent.path }}"
      when:
        - apt_lists_file_absent.path is defined
        - apt_lists_file_absent.state is defined
        - apt_lists_file_absent.state == "absent"
      loop: "{{ apt_lists }}"
      loop_control:
        loop_var: apt_lists_file_absent
        label: "{{ apt_lists_file_absent.path | ansible.builtin.basename | ansible.builtin.regex_replace('[.]lists$') }}"

  tags:
    - apt
...
