# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as apt is false
  ansible.builtin.debug:
    msg: "The apt variable need to be true for the tasks in this role to run."
  when: not apt | bool
  tags:
    - apt

- name: Configure apt sources list for Debian and Ubuntu
  block:

    - name: Include verify variables tasks
      ansible.builtin.include_tasks: verify.yml
      when:
        - apt_verify | bool
        - ansible_version.full is version('2.11', '>=')

    - name: Include local facts tasks
      ansible.builtin.include_tasks: local_facts.yml
      when:
        - apt_local_facts is defined
        - apt_local_facts | bool
        - apt_local_facts_files is defined
        - apt_local_facts_files != []
      tags:
        - apt_local_facts

    - name: Include checks
      ansible.builtin.include_tasks: checks.yml

    - name: Install packages in a block as this task will fail when the sources are not correct
      block:

        - name: Packages present
          ansible.builtin.apt:
            pkg: "{{ apt_pkgs | community.general.json_query(apt_pkgs_jmespath_query) }}"
            update_cache: true
          vars:
            apt_pkgs_jmespath_query: "[?distro=='{{ ansible_distribution_release }}'].pkgs|[0]"

      rescue:

        - name: Package install failed
          ansible.builtin.debug:
            msg: This failure is being ignored as the package install might require a prior update to the apt sources.

    - name: Include apt config tasks
      ansible.builtin.include_tasks: config.yml

    - name: Update the cache when switching distros
      ansible.builtin.apt:
        update_cache: true
      when: >-
        ( apt_distro_switch is defined ) and
        ( apt_distro_switch | bool )

    - name: When switching distros updates should not be done using Ansible
      block:

        - name: Packages upgraded
          ansible.builtin.apt:
            autoclean: true
            autoremove: true
            upgrade: dist
            update_cache: true
          register: apt_dist_upgrade

        - name: Re-read Ansible local facts  # noqa: no-handler
          ansible.builtin.setup:
            filter: ansible_local
          when: apt_dist_upgrade.changed | bool

        - name: Include apticron tasks
          ansible.builtin.include_tasks: apticron.yml
          when: apt_apticron is defined

        - name: Apt clean
          ansible.builtin.include_tasks: apt_clean.yml
          when: ansible_version.full is version('2.13', '>=')

      when: >-
        ( apt_distro_switch is not defined ) or
        ( not apt_distro_switch | bool )

    - name: Include check for legacy .list file
      ansible.builtin.include_tasks: list_check.yml
      tags:
        - apt_list

  when: apt | bool
  tags:
    - apt
...
