---
- name: Print apt_ vars if verbosity 1 or more
  debug:
    msg: "apt_distro: {{ apt_distro }}"
    verbosity: 1
  tags:
    - apt

- name: lsb-release present
  apt:
    pkg: lsb-release
    state: present
  tags:
    - apt

- name: Check the distro version using lsb_release
  shell: "lsb_release -c | awk '{ print $2 }'"
  register: apt_version_check
  changed_when: false
  check_mode: false
  tags:
    - apt

- name: Fail if the checked distro version doesn't match the specified value of apt_distro
  fail:
    msg: "The distro was detected as {{ apt_version_check.stdout }} but you are asking for the server to be configured for {{ apt_distro }}."
  when: ( apt_distro != apt_version_check.stdout ) and ( apt_distro_switch == False )
  tags:
    - apt

- name: Warning and tasks for switching distros
  block:

    - name: Print a warning the the distro is being changed
      debug:
        msg: "WARNING: Updating distro from {{ apt_version_check.stdout }} to {{ apt_distro }}."
      tags:
        - apt

    - name: Run apt-get --allow-releaseinfo-change update
      shell: apt-get --allow-releaseinfo-change update
      tags:
        - apt

  when: apt_distro_switch == True

- name: Set apt_distro if not defined
  set_fact:
    apt_distro: "{{ apt_version_check.stdout }}"
  when: apt_distro is not defined
  tags:
    - apt

- name: Load package information as facts
  package_facts:
    manager: apt
  tags:
    - apt

- name: Fail if ansible_facts.packages is not defined or empty
  fail:
    msg: The package_facts array is empty, this could be a result of the Ansible 2.8.x bug https://github.com/ansible/ansible/issues/56921
  when: ( ansible_facts.packages is not defined ) or ( ansible_facts.packages == [] )
  tags:
    - apt

- name: Include Debian tasks
  include_tasks: debian.yml
  when: ( apt_distro == "buster" ) or ( apt_distro == "stretch" ) or ( apt_distro == "jessie" )
  tags:
    - apt

- name: Include Ubuntu tasks
  include_tasks: ubuntu.yml
  when: ( apt_distro == "bionic" ) or ( apt_distro == "xenial" )
  tags:
    - apt

- name: Update the cache when switching distros
  apt:
    update_cache: true
  when: ( apt_distro_switch is defined ) and ( apt_distro_switch == True )
  tags:
    - apt

- name: When switching distros updates should not be done via Ansible
  block:

    - name: Packages upgraded
      apt:
        autoclean: true
        autoremove: true
        upgrade: dist
        update_cache: true
      tags:
        - apt

    - name: Packages present
      apt:
        pkg:
          - apticron
          - aptitude
          - apt-listchanges
          - apt-show-versions
          - python-apt
        state: present
        update_cache: false
      tags:
        - apt

  when: ( apt_distro_switch is not defined ) or ( apt_distro_switch == False )
...
