---
- name: Print apt_ vars if verbosity 1 or more
  debug:
    msg: 
     - "apt_distro: {{ apt_distro }}"
     - "apt_backports: {{ apt_backports }}"
     - "apt_src: {{ apt_src }}"
    verbosity: 1

- name: Include Debian tasks
  include_tasks: debian.yml
  when: ( apt_distro == "buster" ) or ( apt_distro == "stretch" ) or ( apt_distro == "jessie" )
