---
- name: Debug vars
  debug:
    msg: 
     - "Apt Distro: {{ apt_distro }}"
     - "Apt Backports: {{ apt_backports }}"
     - "Apt Src: {{ apt_src }}"
    verbosity: 1

- name: Include Debian tasks
  include_tasks: debian.yml
  when: ( apt_distro == "buster" ) or ( apt_distro == "stretch" ) or ( apt_distro == "jessie" )
