---
- name: /etc/apt/sources.list in place
  template:
    src: templates/ubuntu_sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    backup: true
  tags:
    - apt

- name: /etc/apt.conf in place
  template:
    src: templates/apt.conf.j2
    dest: /etc/apt.conf
    mode: 0644
    backup: true
  tags:
    - apt
...
