---
- name: Ubuntu tasks
  block:

    - name: /etc/apt/sources.list in place
      ansible.builtin.template:
        src: templates/ubuntu_sources.list.j2
        dest: /etc/apt/sources.list
        mode: 0644
        owner: root
        group: root
        backup: true

    - name: /etc/apt.conf in place
      ansible.builtin.template:
        src: templates/apt.conf.j2
        dest: /etc/apt.conf
        mode: 0644
        owner: root
        group: root
        backup: false

  tags:
    - apt
...
