# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify variables
  block:

    - name: Debug the hostvars variable names that start with apt_  # noqa: no-role-prefix
      ansible.builtin.debug:
        var: aptvarnames
        verbosity: "{% if ansible_check_mode | bool %}3{% else %}4{% endif %}"

    - name: Debug the hostvars variable names that start with apt_  # noqa: no-role-prefix
      ansible.builtin.debug:
        var: apthostvars
        verbosity: "{% if ansible_check_mode | bool %}3{% else %}4{% endif %}"

    - name: Set a fact for the argument spec and internal argument spec  # noqa: no-role-prefix
      ansible.builtin.set_fact:
        apt_argument_spec: "{{ (lookup('ansible.builtin.file', 'meta/argument_specs.yml') | from_yaml) }}"
        apt_internal_argument_spec: "{{ (lookup('ansible.builtin.file', 'meta/internal_argument_specs.yml') | from_yaml) }}"

    - name: Set a fact for the combined argument spec and internal argument spec
      ansible.builtin.set_fact:
        apt_combined_argument_spec: "{{ apt_argument_spec | ansible.builtin.combine(apt_internal_argument_spec, recursive=true) }}"

    - name: Check apt_ variables using the combined argument spec  # noqa: no-role-prefix
      ansible.builtin.validate_argument_spec:
        argument_spec: "{{ apt_combined_argument_spec['argument_specs']['main']['options'] }}"
        provided_arguments: "{{ apthostvars }}"

  when: apt_verify | bool
  tags:
    - apt
...
