# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Check if /etc/apt/sources.list exists
      ansible.builtin.stat:
        path: /etc/apt/sources.list
      register: molecule_apt_sources_list

    - name: Slurp and print /etc/apt/sources.list
      block:

        - name: Slurp /etc/apt/sources.list
          ansible.builtin.slurp:
            src: /etc/apt/sources.list
          register: molecule_apt_sources_list_b64encoded

        - name: Decode the base64 encoded version of /etc/apt/sources.list
          ansible.builtin.set_fact:
            molecule_apt_sources_list_content: "{{ molecule_apt_sources_list_b64encoded['content'] | b64decode | trim }}"
            molecule_apt_sources_list_content_lines: "{{ molecule_apt_sources_list_b64encoded['content'] | b64decode | trim | split('\n') }}"

        - name: Print the contents of the /etc/apt/sources.list lines
          ansible.builtin.debug:
            var: molecule_apt_sources_list_content_lines

      when: molecule_apt_sources_list.stat.exists | bool

    - name: Check if /etc/apt/sources.list.d/debian.sources exists
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/debian.sources
      register: molecule_apt_sources_debian

    - name: Find all .list and .sources files in /etc/apt/sources.list.d
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d
        recurse: false
        patterns:
          - '*.list'
          - '*.sources'
      register: molecule_apt_sources_list_d

    - name: Set a fact for the paths of all the files in /etc/apt/sources.list.d
      ansible.builtin.set_fact:
        molecule_apt_sources_list_d_paths: "{{ molecule_apt_sources_list_d.files | community.general.json_query('[].path') | default([]) }}"

    - name: Debug the paths of all files in /etc/apt/sources.list.d
      ansible.builtin.debug:
        var: molecule_apt_sources_list_d_paths

    - name: Warn that the next job will fail
      ansible.builtin.debug:
        msg: The next job will fail with 'NoneType' object is not iterable. this is safe to ignore.
      when: molecule_apt_sources_list_d_paths == []

    - name: Slurp and print .list and .sources files in /etc/apt/sources.list.d
      block:

        - name: Slurp all the .list and .sources files in /etc/apt/sources.list.d
          ansible.builtin.slurp:
            path: "{{ molecule_apt_sources_list_d_path }}"
          loop: "{{ molecule_apt_sources_list_d_paths | list }}"
          loop_control:
            loop_var: molecule_apt_sources_list_d_path
            label: "{{ molecule_apt_sources_list_d_path | ansible.builtin.basename }}"
          register: molecule_apt_sources_list_d_b64encoded

        - name: Debug molecule_apt_sources_list_d_b64encoded.results
          ansible.builtin.debug:
            var: molecule_apt_sources_list_d_b64encoded

        - name: Debug
          ansible.builtin.debug:
            msg: "{{ molecule_apt_sources_list_d_b64encoded.results | community.general.json_query('[].content') | map('ansible.builtin.b64decode') }}"

        - name: Debug the content of the .list and .sources files in /etc/apt/sources.list.d
          ansible.builtin.debug:
            msg: "{{ molecule_apt_sources_list_d_b64 | ansible.builtin.b64decode }}"
          loop: "{{ molecule_apt_sources_list_d_b64encoded.results | community.general.json_query('[].content')  }}"
          loop_control:
            extended: true
            loop_var: molecule_apt_sources_list_d_b64
            label: "{{ ansible_loop.index }}"
          when:
            - molecule_apt_sources_list_d_b64encoded.results is defined
            - molecule_apt_sources_list_d_b64encoded.results != []

      rescue:

        - name: This failure is probably safe to ignore
          ansible.builtin.debug:
            msg: If the failure was caused by the list of files paths being empty it is safe to ignore it.

      when:
        - molecule_apt_sources_list_d_paths is defined
        - molecule_apt_sources_list_d_paths != []
        - molecule_apt_sources_list_d_paths | length > 0

    - name: Run apt-get update  # noqa: no-changed-when
      ansible.builtin.command: apt-get update
      register: molecule_apt_get_update
      changed_when: false

    - name: Debug the results from apt-get update
      ansible.builtin.debug:
        var: molecule_apt_get_update.stdout_lines

    - name: Run apt-get upgrade -y  # noqa: no-changed-when
      ansible.builtin.command: apt-get upgrade -y
      register: molecule_apt_get_upgrade
      changed_when: ("0 upgraded" not in molecule_apt_get_upgrade.stdout)
      failed_when: molecule_apt_get_upgrade.stderr | length > 0

    - name: Debug the results from apt-get upgrade -y
      ansible.builtin.debug:
        var: molecule_apt_get_upgrade.stdout_lines
...
