# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects apt Ansible role.
#
# The Webarchitects apt Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects apt Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects apt Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Check if /etc/apt/sources.list exists
      ansible.builtin.stat:
        path: /etc/apt/sources.list
      register: molecule_apt_sources_list

    - name: Slurp and print /etc/apt/sources.list
      block:

        - name: Slurp /etc/apt/sources.list
          ansible.builtin.slurp:
            src: /etc/apt/sources.list
          register: molecule_apt_sources_list_b64encoded

        - name: Decode the base64 encoded version of /etc/apt/sources.list
          ansible.builtin.set_fact:
            molecule_apt_sources_list_content: "{{ molecule_apt_sources_list_b64encoded['content'] | b64decode | trim }}"
            molecule_apt_sources_list_content_lines: "{{ molecule_apt_sources_list_b64encoded['content'] | b64decode | trim | split('\n') }}"

        - name: Print the contents of the /etc/apt/sources.list lines
          ansible.builtin.debug:
            var: molecule_apt_sources_list_content_lines

      when: molecule_apt_sources_list.stat.exists | bool

    - name: Check if /etc/apt/sources.list.d/debian.sources exists
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/debian.sources
      register: molecule_apt_sources_debian

    - name: Slurp and print /etc/apt/sources.list.d/debian.sources
      block:

        - name: Slurp /etc/apt/sources.list.d/debian.sources
          ansible.builtin.slurp:
            src: /etc/apt/sources.list.d/debian.sources
          register: molecule_apt_sources_debian_b64encoded

        - name: Decode the base64 encoded version of /etc/apt/sources.list
          ansible.builtin.set_fact:
            molecule_apt_sources_debian_content: "{{ molecule_apt_sources_debian_b64encoded['content'] | b64decode | trim }}"
            molecule_apt_sources_debian_content_lines: "{{ molecule_apt_sources_debian_b64encoded['content'] | b64decode | trim | split('\n') }}"

        - name: Print the contents of the /etc/apt/sources.list lines
          ansible.builtin.debug:
            var: molecule_apt_sources_debian_content_lines

      when: molecule_apt_sources_debian.stat.exists | bool

    - name: Find all files in /etc/apt/sources.list.d
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d
      register: molecule_apt_sources_list_d

    - name: Debug the results from finding all files in /etc/apt/sources.list.d
      ansible.builtin.debug:
        var: molecule_apt_sources_list_d

    - name: Debug the paths of all files in /etc/apt/sources.list.d
      ansible.builtin.debug:
        var: molecule_apt_file.path
      loop: "{{ molecule_apt_sources_list_d.files }}"
      loop_control:
        extended: true
        label: "{{ ansible_loop.index }}"
        loop_var: molecule_apt_file

    - name: Run apt-get update  # noqa: no-changed-when
      ansible.builtin.command: apt-get update
      register: molecule_apt_get_update

    - name: Debug the results from apt-get update
      ansible.builtin.debug:
        var: molecule_apt_get_update

    - name: Run apt-get upgrade -y  # noqa: no-changed-when
      ansible.builtin.command: apt-get upgrade -y
      register: molecule_apt_get_upgrade

    - name: Debug the results from apt-get upgrade -y
      ansible.builtin.debug:
        var: molecule_apt_get_upgrade
...
